name: app-ci 

on:
  push:
    branches: 
      - main
      - release*
    paths-ignore: 
      - .github/**

env:
  server: ${{ secrets.AZURE_CONTAINER_REGISTRY }}
  username: ${{ secrets.ACR_USERNAME }}
  password: ${{ secrets.ACR_PASSWORD }}
  repository: frontend

jobs:
  build-test:
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.image.outputs.image }}
    steps:
      - name: Clone repo
        uses: actions/checkout@v4
      - name: Building the image name
        id: image
        run: |
          echo "image=${{ env.server }}/${{ env.repository }}:${{ github.ref_name }}-${{ github.run_number }}" >> "$GITHUB_OUTPUT"
      - name: Build the docker image
        run: docker build . -t ${{ steps.image.outputs.image }}
      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.server }}
          username: ${{ env.username }}
          password: ${{ env.password }}
      - name: Push the docker image
        run: docker push ${{ steps.image.outputs.image }}

  deploy-dev:
    if:  contains(github.ref_name, 'main')
    needs: build-test
    environment: development
    runs-on: ubuntu-22.04
    steps:
      - name: Login to Azure Container Registry
        uses: azure/docker-login@v2
        with:
          login-server: ${{ env.server }}
          username: ${{ env.username }}
          password: ${{ env.password }}
      - name: deploy
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ secrets.APP_NAME }}
          publish-profile: ${{ secrets.PUBLISH_PROFILE }}
          images: ${{needs.build-test.outputs.image}}
     

  deploy-test:
    if:  contains(github.ref_name, 'release')
    needs: build-test
    environment: testing
    runs-on: ubuntu-22.04
    steps:
      - name: Login to Azure Container Registry
        uses: azure/docker-login@v2
        with:
          login-server: ${{ env.server }}
          username: ${{ env.username }}
          password: ${{ env.password }}
      - name: deploy
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ secrets.APP_NAME }}
          publish-profile: ${{ secrets.PUBLISH_PROFILE }}
          images: ${{needs.build-test.outputs.image}}